version: '3.3'

services:
    reverseproxy:
        image: reverseproxy
        ports:
          - 80:80
        restart: always

    frontend:
        depends_on:
          - reverseproxy
        image: nginx:alpine
        restart: always

    backend:
        depends_on:
          - reverseproxy
        image: httpd:alpine
        restart: always
